version: '3'

services:
  db:
    image: mongo:3.6
    ports:
      - "27017:27017"
    command: mongod --storageEngine wiredTiger

  api:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8887
    volumes:
      - ./b2w:/codigo
    ports:
      - "8887:8887"
    depends_on:
      - db
    environment:
      MONGODB_HOST: db
    links:
      - db

      #links:
    #  - wdb
  #wdb:
  #  image: kozea/wdb
  #  ports:
  #  - "1984:1984"