# Generated by Django 2.0 on 2019-02-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('climate', models.TextField(null=True)),
                ('terrain', models.TextField(null=True)),
            ],
        ),
    ]
